### ISSUE TITLE
Array needs to be reset after each call

### ISSUE THREAD

**Issue by riyadali** [cwlsn/ics-to-json#1]
Thanks for this easy to use utility function.  I was able to successful incorporate it into my project to parse ics type files.  I found one minor issue when using it.  I had several files to parse and the array being returned with the JSON data was not cleared between calls so I needed to manually " clear the array after each call as follows
``` xs.length=0; ```

For your reference below is a segment of the actual chain of promises ( icsParser.default(xxx) is the call to your utility function)

```
     icsParser.default(val1).then((xs:IIcsCalendarEvent[])  => {             
        evnts1=xs.map(x=>self.createCustomEvent(x,colors.blue));
        xs.length=0;  // code I needed to add to flush the array before the next call
        return "astring";
      }).then(parm1=>{
            icsParser.default(val2).then((xs:IIcsCalendarEvent[])  => {                       
              let evnts2=xs.map(x=>self.createCustomEvent(x,colors.yellow));
               xs.length=0;  // code I needed to add to flush the array before the next call
              self.evnts=evnts1.concat(evnts2);            
              return "astring";
            }).then(....```

**Comment by cwlsn** [comment]
Try updating to `1.0.0` and let me know if that works for you. Thanks for the report :)

**Comment by riyadali** [comment]
I'm using the latest version of Angular (7.0 with typescript) and I wasn't able to test it easily because the interface for the function has changed significantly.  In previous versions, a Promise<Array<any>> was returned. It appears that the interface has been simplified and now just an Array<any> is returned.  So you don't need to worry about working with promises -- just a simple array.  

If this change to the interface is permanent, I'll spend some time to rework it (I don't think it will be a major hassle) and I'll let you know.  For reference, below is the existing code that generates the promise chain. I tried to make it generic enough so that it can handle parsing any number of calendars.  

To make this work in Angular, I also needed to define the following in  src/typings.d.ts (basically to inform angular that the imported javascript "ics-to-json" defines a function called "default" which returns Promise<IIcsCalendarEvent[]>
```
declare module "ics-to-json"{ 
   /* export function icsToJson(p: string): any; */
   export default function (string) : Promise<IIcsCalendarEvent[]>;
}

interface IIcsCalendarEvent {
  startDate: string;
  endDate: string;
  description: string;
  summary: string;
  location: string;
}
```

Here's the important part of the code to use the older version of your package
```
import "regenerator-runtime/runtime.js";
import * as icsParser from 'ics-to-json';

const cal1Subscribe = this.http.get(
          '/common/modules/iCalendar/iCalendar.aspx', 
          {headers: httpHeaders, params: params1, responseType: 'text'});

const cal2Subscribe = this.http.get(
          '/common/modules/iCalendar/iCalendar.aspx', 
          {headers: httpHeaders, params: params2, responseType: 'text'});

forkJoin(cal1Subscribe,cal2Subscribe).subscribe(([val1,val2] : string[]) => { 
      this.processCalendarData([val1,val2], [colors.blue, colors.yellow], 1, []).then(resArray => {
          self.evnts=resArray;          
        }); /* end then processCalendarData */      
    }); /* end forkJoin subscribe */
  }
  
  processCalendarData(calArray: Array<string>, colorArray: Array<any>, arrIndex: number, resultsArray: Array<CalendarEvent<ExtraEventData>>) : Promise<Array<CalendarEvent<ExtraEventData>>> {
    let createCalFunc=this.createEvents(calArray[arrIndex], colorArray[arrIndex], resultsArray);
    let self=this;
    if (arrIndex==0)
      return createCalFunc;
    else
      return createCalFunc.then(resultsArr => {
          return self.processCalendarData(calArray, colorArray, arrIndex-1, resultsArr);
        });
  }
  // Note having color defined as any is a bit shaky ... but it is ok for now
  createEvents(calData : string, clr : any, resultsArray: Array<CalendarEvent<ExtraEventData>>) : Promise<Array<CalendarEvent<ExtraEventData>>> {
      return icsParser.default(calData).then((xs:IIcsCalendarEvent[])  => {
        let y=resultsArray.concat(xs.map(x=>this.createCustomEvent(x,clr))); 
        xs.length=0;  // need to do this because ics-to-json does not reset array after each call
        return y;
      }); /* end then */
  }

  createCustomEvent(cevent : IIcsCalendarEvent, clr : any) : CalendarEvent<ExtraEventData> {
    return {
             title: cevent.summary,
             start: this.convertVCalendarDate(cevent.startDate),
             color: clr,                
             meta: {  
                    curDay: new Date()
                   }
          }; /* end return */
  }
```

**Comment by cwlsn** [comment]
That's odd it was returning a promise. The intention has always been a to take the ICS data as a string and return the results synchronously. Even in `0.2.1` there was no Promise calls or async code. The returned Promise may have been to do with the Angular implementation- I am not familiar with Angular at all.

I'll put TypeScript support on the todo list!

**Comment by riyadali** [comment]
I am also relatively new to Angular as well as Javascript.  Maybe the
method I am using to invoke your function is not wholly Kosher.  But after
several attempts, the code that I included previously was what worked.
When I upgraded to your new version I was getting an error from Typescript
indicating that "then" is not allowed on "default" (i.e. your icsToJson
function) because it was not a "promise".  Using the older version of your
code, I also needed to import regenerator-runtime as a dependency.

I'll work on upgrading my code to use the new version and will let you know
what happens.

**Comment by cwlsn** [comment]
I'll do some more integration testing and make sure the Babel env is correct and the conversion is returning what I intend.

**Comment by riyadali** [comment]
I believe that my code is using whatever you have defined in dist.js.  It
doesn't appear to use any of the other stuff you have in your main folder.

Actually, when I was trying things out initially, I just copied what you
had in dist.js to my project and then used it that way until I got it to
work.  At that point I imported it as follows from your project (with the
appropriate typings in the src/typings.d.ts)

import * as icsParser from 'ics-to-json';

And then made the call to your function as follows

icsParser.default(calData).then(...)

But as I indicated before I could be doing this all wrong.  If you know of
a better way, let me know.

**Comment by riyadali** [comment]
I was able to get it to work with ics-to-json at the 1.0.0 level and the good part is that promises were not needed and I also did not need regenerator/runtime as an additional dependency.  So as far as I'm concerned this item is resolved (even the original problem about the returned array not being reset).

For the assistance of anyone on Angular who needs to use this function, I'm including below the code that works.  I'm on Angular 7.0.0 with typescript 3.1.3.  The following changes were made to invoke the icsToJson function

1) Update your typings to define what entities are being included by the import of "ics-to-json".  You can define a separate file called src/ics-to-json.d.ts (I believe that the name, i.e. "ics-to_json", must match what is on your import statement) or you can add your typings to the general typings file  src/typings.d.ts.

```
declare module "ics-to-json"{   
   export default function (string) : Array<IIcsCalendarEvent>;
}

interface IIcsCalendarEvent {
  startDate: string;
  endDate: string;
  description: string;
  summary: string;
  location: string;
}
```

2) In the component where you need to parse the ICS data just use the import below to include icsToJson
```
import * as icsParser from 'ics-to-json';
```

You can then use the function as follows, where icsParser.default(calData) is a call to the icsToJson function which returns an Array of IIcsCalendarEvent objects (defined in the typings file)  

```
... setup headers and params ...
this.http.get(
          '/common/modules/iCalendar/iCalendar.aspx', 
          {headers: httpHeaders, params: params1, responseType: 'text'})).subscribe(calData=>{
               calEvents=icsParser.default(calData);
         })

```

For reference, a more complete version of source code is included below.  This version allowed me to process multiple calendar files and  also includes a mapping function, createCustomEvent, to transform the array returned by icsToJson into something more suitable for my application.  Basically, I needed to attach a color attribute and some meta data to each calendar event.

```
let httpHeaders = new HttpHeaders().set('Accept', 'text/calendar');

... setup params for http.get ...

const cal1Subscribe = this.http.get(
          '/common/modules/iCalendar/iCalendar.aspx', 
          {headers: httpHeaders, params: params1, responseType: 'text'});
const cal2Subscribe = this.http.get(
          '/common/modules/iCalendar/iCalendar.aspx', 
          {headers: httpHeaders, params: params2, responseType: 'text'});

// you can add more calendar data feeds if necessary.  The code is generic enough to handle more
// than 2 feeds.  Just remember to include any new feeds in the forkJoin below

forkJoin(cal1Subscribe,cal2Subscribe).subscribe((icsArray : string[]) => {
      this.evnts=this.processCalendarData(icsArray, [colors.blue, colors.yellow], 
                            icsArray.length-1);     
    }); /* end forkJoin subscribe */

processCalendarData(calArray: Array<string>, colorArray: Array<any>, 
                   arrIndex: number) : Array<CalendarEvent<ExtraEventData>> {
    let calEvents=this.createEvents(calArray[arrIndex], colorArray[arrIndex]);    
    if (arrIndex==0)
      return calEvents;
    else
      return calEvents.concat(this.processCalendarData(calArray, colorArray, arrIndex-1));      
  }
  
  // Note having color defined as any is a bit shaky ... but it is ok for now
  createEvents(calData : string, clr : any) : Array<CalendarEvent<ExtraEventData>> {
      return icsParser.default(calData).map(x=>this.createCustomEvent(x,clr));
  }

  createCustomEvent(cevent : IIcsCalendarEvent, clr : any) : CalendarEvent<ExtraEventData> {
    return {
             title: cevent.summary,
             start: this.convertVCalendarDate(cevent.startDate),
             color: clr,            
             meta: {  
                    curDay: new Date()
                   }
          }; /* end return */
  }

convertVCalendarDate(vdate:string) : Date {  
    let reggie = /(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z/,
        [, year, month, day, hours, minutes, seconds] = reggie.exec(vdate)

    return new Date(Date.UTC(parseInt(year), parseInt(month)-1, parseInt(day), 
                              parseInt(hours), parseInt(minutes), parseInt(seconds)))
  }
```

**Comment by cwlsn** [comment]
Awesome, I'll keep this in mind if another Angular issue pops up. Thanks for issue #1!
